import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{LayoutDashboard,Boxes,SlidersHorizontal,MonitorCog,ShieldCheck,Lightbulb,Bookmark,Settings,LogOut,Menu,Search,Trash2,Save,RotateCcw,CheckCircle2,AlertTriangle,XCircle,ChevronRight,Lock,Plus}from'lucide-react';
import'./styles.css';
import{components,workloads,qfdRelationships,defaultReqs}from'./data/data.js';
import{runQfd}from'./logic/qfd.js';
import{analyzeBuild}from'./logic/analysis.js';
import{recommend}from'./logic/recommend.js';
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0);
const buildKeys=['cpu','motherboard','ram','gpu','storage','psu','case'];
const fields={CPU:'cpu',Motherboard:'motherboard',RAM:'ram',GPU:'gpu',Storage:'storage',PSU:'psu',Case:'case'};
const navGroups=[
 {label:'BUILD',items:[['Home',LayoutDashboard],['Workload Evaluation',SlidersHorizontal],['Components',Boxes],['Build Configuration',MonitorCog]]},
 {label:'ANALYSIS',items:[['Dashboard',LayoutDashboard],['QFD Analysis',MonitorCog],['Compatibility & Analysis',ShieldCheck],['FMEA Risk Analysis',AlertTriangle],['Recommendations',Lightbulb]]},
 {label:'SAVED',items:[['My Builds',Bookmark]]},
 {label:'SYSTEM',items:[['Administration',Settings]]}
];
const locked=new Set(['Dashboard','QFD Analysis','Compatibility & Analysis','FMEA Risk Analysis','Recommendations','My Builds','Administration']);
const countSelected=b=>buildKeys.filter(k=>Boolean(b[k])).length;
function App(){
 const[logged,setLogged]=useState(()=>localStorage.getItem('pbb_session_v4')==='1');
 const[page,setPage]=useState('Home');
 const[collapsed,setCollapsed]=useState(false);
 const[authOpen,setAuthOpen]=useState(false);
 const[authTarget,setAuthTarget]=useState('Dashboard');
 const[work,setWork]=useState(()=>JSON.parse(localStorage.getItem('pbb_work_v4')||'[]'));
 const[req,setReq]=useState(()=>JSON.parse(localStorage.getItem('pbb_req_v4')||JSON.stringify(defaultReqs)));
 const[build,setBuild]=useState(()=>JSON.parse(localStorage.getItem('pbb_active_build_v4')||'{}'));
 const[saved,setSaved]=useState(()=>JSON.parse(localStorage.getItem('pbb_saved_v4')||'[]'));
 const qfd=useMemo(()=>runQfd(req,qfdRelationships),[req]);
 const analysis=useMemo(()=>analyzeBuild(build,components,work),[build,work]);
 const recs=useMemo(()=>recommend(build,work,qfd,analysis,components),[build,work,qfd,analysis]);
 useEffect(()=>localStorage.setItem('pbb_work_v4',JSON.stringify(work)),[work]);
 useEffect(()=>localStorage.setItem('pbb_req_v4',JSON.stringify(req)),[req]);
 useEffect(()=>localStorage.setItem('pbb_active_build_v4',JSON.stringify(build)),[build]);
 useEffect(()=>localStorage.setItem('pbb_saved_v4',JSON.stringify(saved)),[saved]);
 const requestLogin=target=>{setAuthTarget(target||'Dashboard');setAuthOpen(true)};
 const go=n=>{if(locked.has(n)&&!logged){requestLogin(n);return}setPage(n)};
 const newBuild=()=>{setBuild({});setWork([]);setReq({...defaultReqs});setPage('Workload Evaluation')};
 const doLogin=()=>{localStorage.setItem('pbb_session_v4','1');setLogged(true);setAuthOpen(false);setPage(authTarget||'Dashboard')};
 const logout=()=>{localStorage.removeItem('pbb_session_v4');setLogged(false);setPage('Home')};
 return <div className={'app '+(collapsed?'collapsed':'')}>
  <aside className="sidebar">
   <div className="brand"><div className="logo">PB</div>{!collapsed&&<div className="brand-copy"><b>PC Build Bench</b><span>PC configuration</span></div>}<button className="collapse" onClick={()=>setCollapsed(!collapsed)}><Menu size={17}/></button></div>
   <nav>{navGroups.map(g=><div className="nav-group" key={g.label}><div className="nav-group-label">{!collapsed&&g.label}</div>{g.items.map(([n,I])=><button key={n} className={page===n?'active':''} title={n} onClick={()=>go(n)}><I size={16}/>{!collapsed&&<span>{n}</span>}{!collapsed&&locked.has(n)&&!logged&&<Lock size={12} className="lock"/>}</button>)}</div>)}</nav>
   <div className="sidebar-bottom">{logged?<button className="signout" onClick={logout}><LogOut size={16}/>{!collapsed&&'Sign out'}</button>:<button className="signout" onClick={()=>requestLogin('Dashboard')}>{!collapsed&&'Sign in'}<ChevronRight size={15}/></button>}</div>
  </aside>
  <main>
   <header className="topbar"><div><div className="section-kicker">PC BUILD BENCH</div><h1>{page}</h1></div><div className="top-actions">{logged?<span className="account-status"><span/>Signed in</span>:<><span className="guest-status">Guest</span><button className="header-signin" onClick={()=>requestLogin('Dashboard')}>Sign in</button></>}</div></header>
   <div className="content"><Page page={page} work={work} setWork={setWork} req={req} setReq={setReq} qfd={qfd} build={build} setBuild={setBuild} analysis={analysis} saved={saved} setSaved={setSaved} recs={recs} setPage={setPage} navigate={go} logged={logged} onLogin={requestLogin} newBuild={newBuild}/></div>
  </main>
  {authOpen&&<Login target={authTarget} onLogin={doLogin} onClose={()=>setAuthOpen(false)}/>} 
 </div>
}
function Login({target,onLogin,onClose}){const[user,setUser]=useState('');const[pass,setPass]=useState('');const submit=e=>{e.preventDefault();if(!user.trim()||!pass.trim())return;onLogin()};return <div className="modal-backdrop"><div className="login-modal"><button className="modal-close" onClick={onClose}><XCircle size={18}/></button><div className="login-mark">PB</div><div className="section-kicker">SIGN IN</div><h2>Continue to {target}</h2><p>Sign in is only used as a local demonstration in this milestone. No account is created on a server.</p><form className="login-form" onSubmit={submit}><label>Username or email<input value={user} onChange={e=>setUser(e.target.value)} autoComplete="username" placeholder="name@example.com"/></label><label>Password<input type="password" value={pass} onChange={e=>setPass(e.target.value)} autoComplete="current-password" placeholder="Enter a password"/></label><button className="primary full" type="submit">Sign in <ChevronRight size={16}/></button></form><button className="text-btn centered" onClick={onClose}>Continue as Guest</button></div></div>}
function Page(p){switch(p.page){case'Home':return <Home {...p}/>;case'Dashboard':return <Dashboard {...p}/>;case'Workload Evaluation':return <Workload {...p}/>;case'QFD Analysis':return <QFD {...p}/>;case'Components':return <ComponentsPage {...p}/>;case'Build Configuration':return <Build {...p}/>;case'Compatibility & Analysis':return <Analysis {...p}/>;case'FMEA Risk Analysis':return <FMEA {...p}/>;case'Recommendations':return <Recommendations {...p}/>;case'My Builds':return <MyBuilds {...p}/>;case'Administration':return <Admin/>;default:return <Home {...p}/>}}
const Status=({type,children})=><span className={'status '+type}>{type==='ok'?<CheckCircle2 size={13}/>:type==='warn'?<AlertTriangle size={13}/>:<XCircle size={13}/>} {children}</span>;
const Metric=({label,value,sub})=><div className="metric"><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>;
const Row=({k,v})=><div className="row"><span>{k}</span><b>{v}</b></div>;
function PageHead({eyebrow,title,children,action}){return <div className="page-head"><div><div className="section-kicker">{eyebrow}</div><h2>{title}</h2>{children&&<p>{children}</p>}</div>{action}</div>}
function Home({setPage,build,analysis,onLogin,newBuild}){const selected=countSelected(build);return <div className="home-page">
 <PageHead eyebrow="PC CONFIGURATION" title="Build your PC.">Start from a workload, browse parts, then assemble a configuration.</PageHead>
 <section className="home-start"><div><span className="quiet-label">NEW BUILD</span><h3>Start with an empty configuration</h3><p>Nothing is preselected. Choose every component yourself.</p><button className="primary" onClick={newBuild}>Start a new build <ChevronRight size={15}/></button></div><div className="home-stats"><div><span>Parts in catalogue</span><b>{components.length}</b></div><div><span>Workload profiles</span><b>{Object.keys(workloads).length}</b></div></div></section>
 <div className="home-grid"><section className="home-section"><div className="section-title-row"><h3>Explore</h3></div><button className="home-link" onClick={()=>setPage('Workload Evaluation')}><SlidersHorizontal size={17}/><span><b>Workload Evaluation</b><small>Choose what the PC will be used for.</small></span><ChevronRight size={15}/></button><button className="home-link" onClick={()=>setPage('Components')}><Boxes size={17}/><span><b>Components</b><small>Browse the catalogue and add parts directly to the build.</small></span><ChevronRight size={15}/></button><button className="home-link" onClick={()=>setPage('Build Configuration')}><MonitorCog size={17}/><span><b>Build Configuration</b><small>Review the selected parts, cost and power estimate.</small></span><ChevronRight size={15}/></button></section><section className="home-section"><div className="section-title-row"><h3>Current build</h3><button className="text-btn" onClick={()=>setPage('Build Configuration')}>Open <ChevronRight size={14}/></button></div><div className="home-current"><div><span>Selected</span><b>{selected}/7</b></div><div><span>Total</span><b>{money(analysis.total)}</b></div><div><span>Power</span><b>{analysis.power} W</b></div></div><div className="mini-parts">{buildKeys.map(k=>{const x=components.find(c=>c.id===build[k]);return <span key={k}>{x?x.name:'—'}</span>})}</div><div className="locked-inline"><span>Detailed analysis</span><button onClick={()=>onLogin('QFD Analysis')}>Sign in <ChevronRight size={13}/></button></div></section></div>
 </div>}
function Dashboard({work,build,analysis,qfd,setPage}){const selected=countSelected(build);return <div><PageHead eyebrow="OVERVIEW" title="Build summary">Review the active configuration and analysis results.</PageHead><div className="metric-grid four"><Metric label="Workloads" value={work.length||0}/><Metric label="Build cost" value={money(analysis.total)}/><Metric label="Estimated power" value={analysis.power+' W'}/><Metric label="QFD coverage" value={Math.round(qfd.coverage)+'%'}/></div><div className="dashboard-grid"><section className="section-block"><div className="section-title-row"><h3>Build status</h3><button className="text-btn" onClick={()=>setPage('Build Configuration')}>Open build <ChevronRight size={14}/></button></div><div className="stack"><Row k="Components selected" v={selected+'/7'}/><Row k="Compatibility" v={<Status type={analysis.compatible?'ok':'bad'}>{analysis.compatible?'Compatible':'Action required'}</Status>}/><Row k="Budget" v={<Status type={analysis.budgetOk?'ok':'warn'}>{analysis.budgetOk?'Within budget':'Over budget'}</Status>}/><Row k="Risk" v={<Status type={analysis.highRisk?'bad':analysis.mediumRisk?'warn':'ok'}>{analysis.highRisk?'High risk':analysis.mediumRisk?'Medium risk':'Low risk'}</Status>}/></div></section><section className="section-block"><div className="section-title-row"><h3>Technical priorities</h3></div><div className="priority-list">{qfd.priorities.slice(0,6).map(x=><div key={x.name}><div><span>{x.name}</span><b>{x.normalized.toFixed(1)}</b></div><div className="bar"><i style={{width:x.normalized+'%'}}/></div></div>)}</div></section></div></div>}
function Workload({work,setWork,navigate}){return <div><PageHead eyebrow="WORKLOAD" title="Choose workloads">Your selections set the workload weighting used later in the analysis.</PageHead><div className="workload-layout"><section className="section-block"><div className="section-title-row"><h3>Workload profiles</h3><span className="quiet-label">Select one or more</span></div><div className="work-list">{Object.entries(workloads).map(([k,v])=><button key={k} className={'work-row '+(work.includes(k)?'selected':'')} onClick={()=>setWork(work.includes(k)?work.filter(x=>x!==k):[...work,k])}><span className="work-check">{work.includes(k)?'✓':''}</span><span><b>{k}</b><small>{v.description}</small></span><strong>{Math.round(v.cpu*100)} CPU · {Math.round(v.gpu*100)} GPU · {Math.round(v.ram*100)} RAM</strong></button>)}</div><div className="button-row"><button className="primary" onClick={()=>navigate('QFD Analysis')}>Continue to QFD <ChevronRight size={15}/></button></div></section><section className="section-block"><div className="section-title-row"><h3>Current mix</h3></div>{work.length?<div className="priority-list">{['cpu','gpu','ram','storage'].map(k=>{const score=work.reduce((s,w)=>s+workloads[w][k],0)/work.length*100;return <div key={k}><div><span>{k.toUpperCase()}</span><b>{Math.round(score)}%</b></div><div className="bar"><i style={{width:score+'%'}}/></div></div>})}</div>:<div className="empty">Select at least one workload.</div>}</section></div></div>}
function QFD({req,setReq,qfd,setPage}){return <div><PageHead eyebrow="QFD ANALYSIS" title="User requirements">Set importance values. The relationship matrix converts them into technical priorities.</PageHead><div className="qfd-layout"><section className="section-block"><div className="section-title-row"><h3>Importance</h3><span className="quiet-label">1 low · 5 critical</span></div>{Object.entries(req).map(([k,v])=><div className="range-row" key={k}><span>{k}</span><b>{v}</b><input type="range" min="1" max="5" value={v} onChange={e=>setReq({...req,[k]:+e.target.value})}/></div>)}<div className="formula">Priority = Σ (importance × relationship strength)</div></section><section className="section-block"><div className="section-title-row"><h3>Technical priorities</h3><span className="quiet-label">Normalized</span></div><div className="priority-list">{qfd.priorities.map(x=><div key={x.name}><div><span>{x.name}</span><b>{x.normalized.toFixed(1)}</b></div><div className="bar"><i style={{width:x.normalized+'%'}}/></div></div>)}</div></section></div><section className="section-block qfd-matrix"><div className="section-title-row"><h3>Relationship matrix</h3><span className="quiet-label">0 none · 1 weak · 3 medium · 9 strong</span></div><div className="matrix"><div className="matrix-head"><span>User / Technical</span>{qfdRelationships.technical.map(t=><span key={t.short}>{t.short}</span>)}</div>{qfdRelationships.users.map(u=><div className="matrix-row" key={u}><span>{u}</span>{qfdRelationships.matrix[u].map((n,i)=><span className={n===9?'strong':n===3?'medium':n===1?'weak':''} key={i}>{n}</span>)}</div>)}</div><div className="matrix-foot"><span>{qfd.explanation}</span><button className="primary" onClick={()=>setPage('Build Configuration')}>Continue to build <ChevronRight size={15}/></button></div></section></div>}
function ComponentsPage({build,setBuild,setPage}){const[c,setC]=useState('All'),[s,setS]=useState('');const cats=['All','CPU','Motherboard','RAM','GPU','Storage','PSU','Case'];const list=components.filter(x=>(c==='All'||x.category===c)&&x.name.toLowerCase().includes(s.toLowerCase()));const pick=x=>setBuild({...build,[fields[x.category]]:x.id});const selected=countSelected(build);return <div><PageHead eyebrow="COMPONENTS" title="Choose parts">Browse by category and add components directly to the active build.</PageHead><section className="build-strip"><div><span>ACTIVE BUILD</span><b>{selected}/7 selected</b></div>{buildKeys.map(k=>{const x=components.find(c=>c.id===build[k]);return <div key={k} className={x?'filled':''}><small>{k}</small><span>{x?x.name:'Not selected'}</span></div>})}<button className="strip-action" onClick={()=>setPage('Build Configuration')}>Open build <ChevronRight size={14}/></button></section><section className="catalog"><div className="catalog-toolbar"><div className="search"><Search size={15}/><input placeholder="Search parts" value={s} onChange={e=>setS(e.target.value)}/></div><div className="chips">{cats.map(x=><button key={x} className={c===x?'chip active':'chip'} onClick={()=>setC(x)}>{x}</button>)}</div></div><div className="catalog-table"><div className="catalog-row catalog-head"><span>Component</span><span>Specifications</span><span>Price</span><span></span></div>{list.map(x=>{const key=fields[x.category],is=x.id===build[key];return <div className={'catalog-row '+(is?'selected-row':'')} key={x.id}><div className="component-name"><span className="tag">{x.category}</span><b>{x.name}</b><small>{x.brand}</small></div><div className="catalog-specs">{Object.entries(x.specs).slice(0,4).map(([k,v])=><span key={k}><small>{k}</small><b>{v}</b></span>)}</div><strong className="price">{money(x.price)}</strong><button className={is?'secondary add-btn':'primary add-btn'} onClick={()=>pick(x)}>{is?<><CheckCircle2 size={14}/> Selected</>:<><Plus size={14}/> Add</>}</button></div>})}</div></section></div>}
function Build({build,setBuild,analysis,logged,onLogin,saved,setSaved}){const update=(k,v)=>setBuild({...build,[k]:v});const saveNow=()=>{if(!logged){onLogin('My Builds');return}if(!build.name){alert('Enter a build name first.');return}setSaved([{...build,id:Date.now(),savedAt:new Date().toLocaleString('en-IN')},...saved.filter(x=>x.name!==build.name)])};return <div><PageHead eyebrow="BUILD CONFIGURATION" title="Assemble the configuration">Select one component in each category and review the live results.</PageHead><div className="builder-layout"><section className="section-block"><div className="section-title-row"><h3>Build details</h3></div><label>Build name<input value={build.name||''} placeholder="e.g. Gaming 1440p" onChange={e=>update('name',e.target.value)}/></label><label>Budget (₹)<input type="number" value={build.budget??80000} min="0" onChange={e=>update('budget',+e.target.value)}/></label><div className="form-section-title">Components</div>{buildKeys.map(k=><label key={k}>{k.replace(/^./,m=>m.toUpperCase())}<select value={build[k]||''} onChange={e=>update(k,e.target.value)}><option value="">Select {k}</option>{components.filter(x=>x.category.toLowerCase()===k).map(x=><option key={x.id} value={x.id}>{x.name} — {money(x.price)}</option>)}</select></label>)}<div className="button-row"><button className="secondary" onClick={()=>setBuild({})}><RotateCcw size={14}/> Reset</button><button className="primary" onClick={saveNow}><Save size={14}/> {logged?'Save build':'Sign in to save'}</button></div></section><section className="section-block"><div className="section-title-row"><h3>Live checks</h3></div><div className="summary-line"><div><span>Total</span><b>{money(analysis.total)}</b></div><div><span>Power</span><b>{analysis.power} W</b></div></div><div className="analysis-list">{analysis.checks.map(c=><div className="analysis-row" key={c.name}><div><b>{c.name}</b><span>{c.detail}</span></div><Status type={c.status}>{c.label}</Status></div>)}</div>{!logged&&<p className="guest-note">Configuration stays available as a guest. Sign in only when saving or opening the detailed analysis tools.</p>}</section></div></div>}
function Analysis({analysis,navigate}){return <div><PageHead eyebrow="COMPATIBILITY" title="Compatibility & analysis">Each result is calculated from the currently selected components.</PageHead><div className="metric-grid four"><Metric label="Build cost" value={money(analysis.total)}/><Metric label="Budget" value={money(analysis.budget)}/><Metric label="Estimated power" value={analysis.power+' W'}/><Metric label="Required PSU" value={analysis.requiredPsu+' W'}/></div><section className="section-block"><div className="analysis-list detailed">{analysis.checks.map(c=><div className="analysis-row" key={c.name}><div className="analysis-icon">{c.status==='ok'?<CheckCircle2 size={18}/>:c.status==='warn'?<AlertTriangle size={18}/>:<XCircle size={18}/>}</div><div className="analysis-copy"><b>{c.name}</b><span>{c.detail}</span></div><Status type={c.status}>{c.label}</Status></div>)}</div></section><div className="actions"><button className="primary" onClick={()=>navigate('FMEA Risk Analysis')}>Run FMEA <ChevronRight size={15}/></button></div></div>}
function FMEA({analysis}){const counts=analysis.fmea.reduce((a,x)=>(a[x.level]=(a[x.level]||0)+1,a),{});return <div><PageHead eyebrow="FMEA" title="Build risk analysis">Severity, Occurrence and Detection are scored from 1–10; RPN = S × O × D.</PageHead><div className="fmea-summary"><Metric label="High" value={counts.High||0}/><Metric label="Medium" value={counts.Medium||0}/><Metric label="Low" value={counts.Low||0}/><Metric label="Highest RPN" value={analysis.fmea[0]?.rpn||0}/></div><section className="section-block"><div className="table-wrap"><table><thead><tr><th>Failure mode</th><th>Effect</th><th>S</th><th>O</th><th>D</th><th>RPN</th><th>Risk</th><th>Mitigation</th></tr></thead><tbody>{analysis.fmea.length?analysis.fmea.map(r=><tr key={r.mode}><td><b>{r.mode}</b></td><td>{r.effect}</td><td>{r.s}</td><td>{r.o}</td><td>{r.d}</td><td><b>{r.rpn}</b></td><td><span className={'risk '+r.level.toLowerCase()}>{r.level}</span></td><td>{r.mitigation}</td></tr>):<tr><td colSpan="8">No applicable failure modes for the current build.</td></tr>}</tbody></table></div></section></div>}
function Recommendations({recs}){return <div><PageHead eyebrow="RECOMMENDATIONS" title="Component suggestions">Rule-based suggestions using workload, QFD priorities, compatibility, budget and power.</PageHead><section className="section-block"><div className="recommend-list">{recs.length?recs.map(r=><article className="recommendation" key={r.title}><div><span className="tag">{r.category}</span><h3>{r.name}</h3><p>{r.reason}</p></div><div className="rec-score"><span>Priority</span><b>{r.score}</b></div></article>):<div className="empty">Set workloads and complete a build to generate recommendations.</div>}</div></section></div>}
function MyBuilds({build,saved,setSaved,setBuild}){const save=()=>{if(!build.name)return alert('Enter a build name first.');setSaved([{...build,id:Date.now(),savedAt:new Date().toLocaleString('en-IN')},...saved.filter(x=>x.name!==build.name)])};return <div><PageHead eyebrow="SAVED BUILDS" title="My builds">Saved configurations are stored locally in this browser.</PageHead><div className="save-bar"><div><b>Save current configuration</b><span>{countSelected(build)}/7 components selected</span></div><button className="primary" onClick={save}><Save size={14}/> Save build</button></div><div className="saved-list">{saved.length?saved.map(x=><div className="saved-row" key={x.id}><div><span className="tag">SAVED</span><h3>{x.name}</h3><small>{x.savedAt}</small></div><div className="saved-meta"><span>{money(x.budget||0)} budget</span><span>{countSelected(x)}/7 parts</span></div><div className="saved-actions"><button className="secondary" onClick={()=>setBuild(x)}><RotateCcw size={14}/> Load</button><button className="danger" onClick={()=>setSaved(saved.filter(y=>y.id!==x.id))}><Trash2 size={14}/></button></div></div>):<div className="empty">No saved builds yet.</div>}</div></div>}
function Admin(){const byCat=components.reduce((a,x)=>(a[x.category]=(a[x.category]||0)+1,a),{});return <div><PageHead eyebrow="SYSTEM" title="Administration">Frontend-only catalogue overview for the 50% milestone.</PageHead><div className="metric-grid four"><Metric label="Catalog items" value={components.length}/><Metric label="Categories" value="7"/><Metric label="Data source" value="Local"/><Metric label="Backend" value="Not implemented"/></div><section className="section-block"><div className="section-title-row"><h3>Categories</h3></div><div className="admin-table">{Object.entries(byCat).map(([k,v])=><div key={k}><b>{k}</b><span>{v} items</span></div>)}</div></section></div>}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
